try full grading path ...

diff --git a/.github/workflows/leaderboard.yml b/.github/workflows/leaderboard.yml
--- a/.github/workflows/leaderboard.yml
+++ b/.github/workflows/leaderboard.yml
@@ -149,19 +149,19 @@ jobs:
           echo "Workspace: $WORKSPACE"
           ls -la "$WORKSPACE"
 
-      - name: Debug before Docker run
-        run: |
-          echo "=== DEBUG VARIABLES ==="
-          echo "Username: ${{ steps.download-artifact.outputs.github_username }}"
+      # - name: Debug before Docker run
+      #   run: |
+      #     echo "=== DEBUG VARIABLES ==="
+      #     echo "Username: ${{ steps.download-artifact.outputs.github_username }}"
           
-          # Check if variables exist
-          if [ -z "${{ steps.download-artifact.outputs.github_username }}" ]; then
-            echo "ERROR: username is EMPTY!"
-          fi
+      #     # Check if variables exist
+      #     if [ -z "${{ steps.download-artifact.outputs.github_username }}" ]; then
+      #       echo "ERROR: username is EMPTY!"
+      #     fi
           
-          echo "=== FILES ==="
-          WORKSPACE="$GITHUB_WORKSPACE/grade_workspace"
-          ls -la "$WORKSPACE" || echo "No workspace"
+      #     echo "=== FILES ==="
+      #     WORKSPACE="$GITHUB_WORKSPACE/grade_workspace"
+      #     ls -la "$WORKSPACE" || echo "No workspace"
 
       - name: Run evaluation in Docker
         id: evaluate
@@ -169,15 +169,16 @@ jobs:
           WORKSPACE="$GITHUB_WORKSPACE/grade_workspace"
           
           
-          for file in ex1_*.py; do
-            TEMP_DB="$WORKSPACE/results_$(basename "$file" .py).db"
+          for file in ${WORKSPACE}/ex1_*.py; do
             GITHUB_USERNAME=$(basename "$file" .py | sed 's/ex1_//')     
-            
+            TEMP_DB="$WORKSPACE/results_${GITHUB_USERNAME}.db"
+
             # Create empty database
             sqlite3 "$TEMP_DB" "VACUUM;" 2>/dev/null || true
             
-            echo "Running evaluation for $file"
+            echo "Running evaluation for : $file"
             echo "Database path: $TEMP_DB"
+            echo "GitHub username: $GITHUB_USERNAME"
             
             # Run Docker with proper user mapping
             docker run \
